<?php
/**
 * @var \Bold\Checkout\Block\System\Config\Form\Field\ClearState $block
 */
?>

<?= $block->getButtonHtml() ?>

<script type="text/x-magento-init">
    {
        "#clear-state": {
            "Bold_Checkout/js/clear-state": {
                "url": "<?= $block->getClearUrl(); ?>",
                "title": "<?= /* @escapeNotVerified */ __('Confirm Clearing Bold Extension') ?>",
                "content": "<?= /* @escapeNotVerified */ __('This action will remove all previously configured settings, including API token, URLs, and other configurations. The settings in the Bold Checkout Extension and Bold Checkout Extension Advanced Settings sections will be returned to their defaults.') ?>",
                "successMessage": "<?= /* @escapeNotVerified */ __('You have cleared the Bold Extension state.') ?>",
                "failedMessage": "<?= /* @escapeNotVerified */ __('You don\'t have required permissions to clear the Bold Extension state.') ?>"
            }
        }
    }
</script>
