<?php
/** @var \Bold\Checkout\Block\System\Config\Form\Field\OnboardBanner $block */
/** @var Magento\Framework\Escaper $escaper */
$bannerData = $block->getBannerData();
?>

<?php if ($bannerData): ?>
    <div id="bold-checkout-onboard">
        <div>
            <h2><?= $escaper->escapeHtml($bannerData->header) ?></h2>
            <p><?= $escaper->escapeHtml($bannerData->text) ?></p>
        </div>

        <button
            type="button"
            onclick="window.open (
                '<?= $escaper->escapeUrl($bannerData->link) ?>',
                'Bold Account Center',
                'width=1400,height=950')
            ">
            <?= $escaper->escapeHtml($bannerData->button_text) ?>
        </button>
    </div>
<?php endif ?>
