<?php
/**
 * Bold checkout self-hosted template.
 *
 * @var Bold\CheckoutSelfHosted\Block\Checkout $this
 */
try {
    $orderData = $this->getOrderData();
    $orderId = $this->getPublicOrderId();
} catch (Exception $e) {
    echo '<script>window.location.href = "' . $this->getReturnUrl() . '"</script>';
    return;
}
?>
<script>
    window.shopAlias = "<?php echo $this->getShopAlias() ?>";
    window.customDomain = "<?php echo $this->getCustomDomain() ?>";
    window.shopName = "<?php echo $this->getShopName() ?>";
    window.returnUrl = "<?php echo $this->getReturnUrl() ?>";
    window.loginUrl = "<?php echo $this->getLoginUrl() ?>";
    window.headerLogoUrl = "<?php echo $this->getHeaderLogoUrl() ?>";
    window.platformType = "bold_platform";
    window.environment = {
        type: "production",
    };
    window.initializedOrder = {
        data: <?php echo $orderData; ?>
    };
    window.publicOrderId = "<?php echo $orderId; ?>";
    window.shopIdentifier = "<?php echo $this->getShopIdentifier(); ?>";
    window.initializedOrder = <?php echo $orderData; ?>;
</script>
<div id='main'>
    <script src="<?php echo $this->getTemplateUrl() ?>"></script>
</div>
<footer></footer>
